spring.data.neo4j.username=neo4j
spring.data.neo4j.password=secret

# for liquigraph
spring.datasource.url=jdbc:neo4j:http://localhost
spring.datasource.driver-class-name=org.neo4j.jdbc.http.HttpDriver
spring.datasource.username=${spring.data.neo4j.username}
spring.datasource.password=${spring.data.neo4j.password}